// Prompt Enhancement Service using Gemini 2.5 Flash
// Enhances user prompts for better video generation, especially with characters
// Includes Veo-specific content policy guidelines to avoid prompt rejections

import { GoogleGenerativeAI } from '@google/generative-ai'

export interface Character {
  id: string
  name: string
  description: string
  reference_image_url?: string | null
  gcs_image_uri?: string | null
}

export interface PromptEnhancementParams {
  originalPrompt: string
  characters?: Character[]
  hasCharacterImages?: boolean  // Indicates if character images will be sent to the model
  hasStyleReference?: boolean
  styleReferenceType?: 'image' | 'video'
  model: string
  duration: number
  aspectRatio?: string
}

export interface EnhancedPromptResult {
  success: boolean
  enhancedPrompt?: string
  error?: string
  originalPrompt: string
}

// Veo content policy guidelines that Gemini must follow when rewriting prompts.
// These are based on Google's Vertex AI Responsible AI guidelines and observed
// rejection patterns from the Veo API.
const VEO_CONTENT_POLICY = `
CRITICAL — VEO CONTENT POLICY (you MUST follow these rules):

The video will be generated by Google's Veo API, which has strict content filters.
Prompts that violate these policies are REJECTED with error "The prompt could not be
submitted due to the interests of third-party content providers." You must rewrite the
user's prompt to be fully compliant.

MUST AVOID (these cause immediate rejection):
1. CELEBRITY / REAL PERSON NAMES — Never include names of real people (musicians, actors,
   athletes, politicians, influencers, historical figures). Instead, describe the person's
   visual archetype generically: "a charismatic male performer with curly dark hair" not
   "Bad Bunny"; "a confident female pop singer" not "Taylor Swift".
2. BRAND NAMES / TRADEMARKS — Never include brand names (Nike, Apple, Coca-Cola, etc.).
   Describe the product aesthetically: "a sleek black smartphone" not "an iPhone";
   "athletic running shoes" not "Nike Air Max".
3. COPYRIGHTED CHARACTERS — Never reference fictional IP characters by name (Mario,
   Spider-Man, Pikachu, etc.). Describe the visual style generically.
4. SONG / MOVIE / SHOW TITLES — Avoid titles of copyrighted works. Describe the genre,
   mood, or style instead.
5. LOGOS, TEXT OVERLAYS, SUBTITLES — Never ask for on-screen text, brand logos, or
   subtitles. Add "no text overlays, no subtitles" if the prompt might imply text.

DIALOGUE FORMATTING (prevents subtitle rendering):
- Use colon format: Character says: dialogue here (NO quotation marks)
- Keep dialogue under 15 seconds for natural pacing
- Specify "(no subtitles)" when including dialogue

PROMPT STRUCTURE BEST PRACTICES:
- Use present tense, active voice
- Be specific about camera angles, lighting, movement
- Describe one continuous scene (no cuts or scene transitions)
- Specify environmental audio: "ambient city sounds" or "quiet forest ambiance"
- For characters, describe micro-expressions and subtle movements to avoid stiffness
- Aim for 400-800 characters total

If the user's original prompt contains ANY of the prohibited content above, you MUST
replace it with a compliant alternative that preserves the user's creative intent.
For example: "Bad Bunny performing at a concert" becomes "A charismatic Latino performer
with curly dark hair and stylish sunglasses energetically performing on a massive neon-lit
concert stage, crowd cheering, dynamic stage lighting."
`

/**
 * Enhances a user's prompt for video generation using Gemini 2.5 Flash
 *
 * This function:
 * - Sanitizes prompts to comply with Veo's content policy (no celebrity names, brands, etc.)
 * - Incorporates character information (name, description) into the prompt
 * - Adds cinematography details for better video quality
 * - Makes prompts more specific and descriptive
 * - Ensures character consistency when character images are provided
 * - Optimizes prompts for the specific video model being used
 */
export async function enhancePromptWithGemini(
  params: PromptEnhancementParams
): Promise<EnhancedPromptResult> {
  const apiKey = process.env.GOOGLE_AI_API_KEY || process.env.GEMINI_API_KEY

  if (!apiKey) {
    console.warn('[PromptEnhancer] No Gemini API key found, returning original prompt')
    return {
      success: false,
      error: 'Gemini API key not configured',
      originalPrompt: params.originalPrompt,
    }
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey)
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' })

    // Build context for the enhancement
    const hasCharacters = params.characters && params.characters.length > 0
    const characterInfo = hasCharacters
      ? params.characters!.map(c => `- ${c.name}: ${c.description}`).join('\n')
      : ''

    // Create the enhancement prompt
    const enhancementPrompt = `You are an expert video generation prompt engineer. Your task is to enhance user prompts for AI video generation to produce the best possible results while ensuring the prompt complies with the video model's content policy.

${VEO_CONTENT_POLICY}

${hasCharacters ? `CHARACTERS IN THIS VIDEO:
${characterInfo}

The character image(s) will be provided to the video model as reference images. Your enhanced prompt MUST explicitly reference the character by name and integrate them naturally into the scene. These are fictional characters created by the user — their names are safe to use.` : ''}

Original user prompt: "${params.originalPrompt}"

Video generation settings:
- Model: ${params.model}
- Duration: ${params.duration} seconds
- Aspect ratio: ${params.aspectRatio || '16:9'}
${params.hasStyleReference ? `- Style reference: ${params.styleReferenceType} (will be provided to the model)` : ''}

Please enhance this prompt following these guidelines:

1. ${hasCharacters && params.hasCharacterImages ? `The character ${params.characters![0].name} is the main subject. Create a DETAILED prompt (aim for 500-800 characters) that includes: (a) ${params.characters![0].name} and what they're doing, (b) Specific movements and actions in detail, (c) Character's style and appearance, (d) Camera movements and framing, (e) Environment and atmosphere. Example: "${params.characters![0].name} climbs the rocky mountain face at sunset, reaching upward with both hands to grip the next ledge, muscles tensing with effort. Camera slowly tracks alongside ${params.characters![0].name} from a side angle, capturing their expression as golden hour light illuminates the scene..."` : hasCharacters ? `START with full character introduction: "A detailed video of ${params.characters![0].name}, ${params.characters![0].description}, [performing detailed action]..."` : 'Keep and expand upon the core action/scene from the original prompt'}

2. Add rich visual details:
   - Camera movement and angles
   - Lighting and atmosphere
   - Color palette and mood
   - Environmental details

3. Specify motion and cinematography:
   - How subjects move through the scene
   - Camera techniques (tracking, panning, static, etc.)
   - Pacing and energy level

4. Be DETAILED and DESCRIPTIVE (aim for 400-800 characters total):
   - Use vivid, specific language
   - Include sensory details (visual, sound, movement)
   - Describe the full scene with rich imagery

5. Use present tense and active voice

6. ${hasCharacters ? `Describe the character naturally within the scene - focus on their actions, emotions, and role in the narrative` : 'Focus on creating a vivid, film-like scene with cinematic details'}

7. COMPLIANCE CHECK — Before outputting, verify:
   - No real celebrity/person names
   - No brand names or trademarks
   - No copyrighted character names
   - No song/movie/show titles
   - No requests for on-screen text or subtitles
   - Dialogue uses colon format (no quotation marks)
   If ANY violations remain, replace them with generic descriptions.

Output ONLY the enhanced prompt text, nothing else. No explanations, no preamble, no quotation marks.`

    console.log('[PromptEnhancer] Sending prompt to Gemini 2.5 Flash for enhancement...')

    const result = await model.generateContent(enhancementPrompt)
    const response = result.response
    const enhancedPrompt = response.text().trim()

    console.log('[PromptEnhancer] Original prompt:', params.originalPrompt)
    console.log('[PromptEnhancer] Enhanced prompt:', enhancedPrompt)

    return {
      success: true,
      enhancedPrompt,
      originalPrompt: params.originalPrompt,
    }
  } catch (error) {
    console.error('[PromptEnhancer] Error enhancing prompt:', error)

    // If enhancement fails, return original prompt so generation can continue
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
      originalPrompt: params.originalPrompt,
    }
  }
}

/**
 * Helper function to safely get enhanced prompt or fallback to original
 */
export function getPromptToUse(result: EnhancedPromptResult): string {
  return result.success && result.enhancedPrompt
    ? result.enhancedPrompt
    : result.originalPrompt
}
